### PR TITLE
WIP: Stock icon fixes

### PR DESCRIPTION
**Pull request by jclin**
@jameswelle @impurator WIP to fix some problem nounproject SVGs that have been discovered thus far:

[#137490927](https://www.pivotaltracker.com/story/show/137490927) Clock Icon Inserts Cropped 
[#137489895](https://www.pivotaltracker.com/story/show/137489895) Icon is not displayed when inserted
[#138257405](https://www.pivotaltracker.com/story/show/138257405) Import stock icons, that have text elements, as metafiles

These appear to not regress characters rendering, but I'd like to have some automated (integration?) tests. Any thoughts? ideas?

### CODE REVIEW

**Comment by impurator** [comment]
We do have some unit tests for characters, though I haven't looked at what they do.

**Comment by jameswelle** [comment]
Do these result in identical character renderings with the shipping SVG library or different?

**Comment by jclin** [comment]
One of the [SvgRenderer specs](https://github.com/articulate/Desktop/blob/master/Tests/Articulate.Tests.Unit/Characters/Rendering/SvgRendererSpec.cs#L31-L32) is failing with a diff increase of ~44.

**Comment by impurator** [comment]
You could create a standalone project that pulls our assets from dropbox (so you don't have to authenticate via CL) and renders through both the current and the new SVG lib.  I'm not sure what the most effective way to avoid definition collision while running the two different libs would be.

**Comment by impurator** [comment]
@jclin these modifications look good on the surface.  Just need good validation that they're not going to trash our characters.

**Comment by jclin** [comment]
@impurator, I brainstormed with @jameswelle last night and the plan of attack will be to use ImageMagick to [compare](http://www.imagemagick.org/Usage/compare/#compare) one of the more detailed female headshots to make sure hair rendering looks good.

If that works out, I'll write a script that will loop through all illustrated characters and rasterize them into large pngs, one pass with the current library, another with this branch. I'll write another script to compare each pair of pngs, outputting an image highlighting the differences, a gif that toggles between image 'A' and 'B', and the number of absolute errors for quantification.

Finally, if the absolute errors seems to be in a reasonable threshold, we'll probably ask Magnus to give an 👁 test for approval.

**Comment by impurator** [comment]
Sounds good to me.

**Comment by impurator** [comment]
Perhaps we can also modify the script a bit to validate icons post-freeformification.

**Comment by mattreagan29** [comment]
Can anyone advise if this PR will impact the file format (or layout) of realistic character SVGs?

Back in March of last year I noticed the SVG engine we rely on in Storyline Mac renders certain gradient shapes incorrectly if the SVGs were exported from Adobe Illustrator in Windows. Even with identical SVG export settings and input `.AI` files, Adobe Illustrator for Mac produces slightly different SVG files vs. the Windows version.

In order to fix the gradient problems, I had to run batch scripts to re-convert all the realistic character `.AI` artwork into SVGs and republish; unfortunately there wasn't a great solution at code level due to the third-party library. I worked with @jameswelle on this at the time though it was quite a while ago.

I don't have much context on this PR but I'm wondering if this will modify the file formatting of those SVGs?

**Comment by jameswelle** [comment]
No @mattreagan29, we are just addressing similar issues in our 💩 SVG library. We don't plan to modify the SVG character files themselves.

**Comment by mattreagan29** [comment]
Thanks @jameswelle 👍

**Comment by jclin** [comment]
@impurator @jameswelle, 2908 realistic character files were rasterized by the current SVG library and this branch, and the mean difference for all compared realistic characters was 0%. All images, and a spreadsheet summarizing the data can be found [here](https://www.dropbox.com/sh/z0nqm5l46ej28pc/AABz53Z-QJU2gxm1RR8z7-VUa?dl=0).

To test, small [.NET assemblies](https://www.dropbox.com/sh/x2usdxkjtf3gifm/AAAUmzoGIyHqYxWq_P5ko5pya?dl=0) were created as thin wrappers around both versions of the library, and the `SvgRenderer` for characters was pilfered from the Desktop repo.

The wrapper assemblies were then consumed by a Powershell script to render each realistic character as an EMF and then rasterized to a PNG. PNGs that end with `_Shipped.png` were generated by the current SVG lbirary, while ones ending with `_Branched.png` were generated by this branch.

Afterwards, another script used Imagemagick to compare each pair of images, and outputting PNGs ending with `_Diff.png` to highlight any differences. All of the diff images show both versions of the SVG library render characters identically.

However, there are a few caveats.

First, not all realistic characters were rasterized. While all files for female characters were rasterized, the script only made it through the first 11 male characters and partially through male character 12. The SVG library seems to get into a strange state when it is used in quick succession for an automated setting. Unfortunately, I never figured out why.

Second, although both versions of the library rendered the characters identically, the renderings themselves have some quirks. For whatever reason, some of the characters are rendered at the right edge of their bounding boxes, with some being clipped, and others completely outside the bounding box. This does concern me somewhat, but the fact that both versions of the library rendered the files in the same way indicates there could be other layout bugs not related to this branch.

That said, 0% changes across 2908 files does inspire some confidence that no regressions are being introduced with this branch, IMHO.

**Comment by jameswelle** [comment]
Very cool @jclin. I agree it looks like we can be pretty confident that we aren't introducing regressions.

Has the code path where the head & body are combined to create the composite image been tested at all with this new renderer?

**Comment by jclin** [comment]
Ah, good call I forgot about that path.
terminator

**Comment by jclin** [comment]
@jameswelle @impurator CC @rockhymas 

All combinations of female characters were combined and rendered. The results are 0% difference across 14,655 files. There was one combination that yielded a 36% difference (row is yellow) but upon inspection it was a false alarm.

NOTE: I did not render the male characters as it took my scripts ~8 hrs just for the female characters, and imagemagick seems to randomly pick which output stream to write, burning a few hours.
The spreadsheet, scripts, and image dumps are [available for viewing](https://www.dropbox.com/sh/00xaqr1ucyzymtu/AABj5eQnx6lKUpPheavZNCbya?dl=0). 

If this is G2G, all that's left is to [update a spec](https://github.com/articulate/Desktop/blob/master/Tests/Articulate.Tests.Unit/Characters/Rendering/SvgRendererSpec.cs#L31-L32) that will fail but is a false positive according to Imagemagick.

**Comment by jameswelle** [comment]
Sounds good @jclin!

**Comment by rockhymas** [comment]
👍

**Comment by jclin** [comment]
Heads up, will merge this branch and issue another PR to wire up this repo to Appveyor.

**Pull request merged**
