### PR TITLE
Changed nuspec over to static version number

### PR DESCRIPTION
**Pull request by impurator**
This is in line with how we maintain other external packages.

@jameswelle Changing this over to mimic the flow we use for https://github.com/articulate/Articulate.Desktop.Branding

### CODE REVIEW

**Comment by jameswelle** [comment]
@impurator do you want to bump this version instead? https://github.com/articulate/SVG/blob/master/Source/Properties/AssemblyInfo.cs#L35

**Comment by impurator** [comment]
@jameswelle When I run against the nuspec rather than the csproj I get a complaint about the missing token.  I'm not invested either way, just trying to keep our procedures consistent.

**Comment by jameswelle** [comment]
When we build from source we should use AssemblyInfo as we are doing here. To pack in this case you will specify the .csproj instead of the .nuspec as the source argument.

**Comment by impurator** [comment]
Alrighty, can do that.  Do you want me to define a static revision # there or just use the build number, as it's currently configured to do?

**Comment by jameswelle** [comment]
I think leave it as-is but increment 7 to 8?

**Comment by impurator** [comment]
Works for me, repushing in a moment.

**Pull request merged**
